### ISSUE TITLE
Using a different theme/themePath

### ISSUE THREAD

**Issue by Cdk29** [Witiko/fibeamer#2]
Good afternoon.

I have try to use the fibeamer to create a presentation since i find it quite beautifull.

Nonetheless, while I can pass the logo of my own institution using :

`\usetheme[logo=logo.pdf, faculty=phil]{fibeamer}`

I cannot change the theme of the template, using themePath toward a .sty files (without the faculty option enable). I have try to put a more complete path but did not work either, it's just make the whole fibeamer style disappear from the pdf output.

`\usetheme[logo=logo.pdf, thePath=whatever.sty]{fibeamer}`

The sty files being an exact copy of one the style present in theme/mu, with just one color change.

I have installed latex using texlive-full, so I do not need to be in the fibeamer folder download on CTAN to compile.

I think I miss something about how to change the theme/colors despite having read the whole doc, can you give me a clue on how to proceed exactly ?

**Comment by Witiko** [comment]
Hi,

I am sorry to hear about your problems. You should create the following
directory structure:

    $ tree /some/path/where/my/university/theme/is/stored
    /some/path/where/my/university/theme/is/stored
    ├── logo
    │   └── my_university
    │       ├── fibeamer-my_university-my_faculty-english.eps
    │       └── fibeamer-my_university-my_faculty-english.pdf
    └── theme
        └── my_university
            ├── beamercolorthemefibeamer-my_university-my_faculty.sty
            ├── beamercolorthemefibeamer-my_university.sty
            ├── beamerfontthemefibeamer-my_university.sty
            ├── beamerinnerthemefibeamer-my_university.sty
            └── beamerouterthemefibeamer-my_university.sty

Then, you can instruct fibeamer to load your theme as follows:

    \usetheme[
      basePath=/some/path/where/my/university/theme/is/stored,
      university=my_university,
      faculty=my_faculty,
    ]{fibeamer}

Unless you choose to structure your directories differently, there is no
need to set themePath, and logoPath explicitly.

**Comment by Cdk29** [comment]
Good morning.

Thanks for the quick reply. Unfortunately I have not been able to obtain a pdf with the fibeamer style : 

.
├── i3s.aux
├── i3s.log
├── i3s.nav
├── i3s.out
├── i3s.pdf
├── i3s.snm
├── i3s.synctex.gz
├── i3s.tex
├── i3s.toc
├── Jabberwocky.jpg
├── logo
│   └── U_Porto
│       ├── fibeamer-U_Porto-i3s-english.eps
│       └── fibeamer-U_Porto-i3s-english.pdf
└── theme
    └── U_Porto
        ├── beamercolorthemefibeamer-U_Porto-i3s.sty
        ├── beamercolorthemefibeamer-U_Porto.sty
        ├── beamerfontthemefibeamer-U_Porto.sty
        ├── beamerinnerthemefibeamer-U_Porto.sty
        └── beamerouterthemefibeamer-U_Porto.sty

```
\usetheme[basePath=/home/erolland/Desktop/fibeamer/theme/U_Porto,
university=U_Porto,
faculty=i3s,]{fibeamer}
```

While i3s is an institute and not a faculty, I doubt that fibeamer is aware of that :D 

More seriously, the pdf output arbor a simple and sad beamer look, with not even the logo of the institute.
Is there something obvious that I am doing wrong here ?

**Comment by Witiko** [comment]
The `basePath` should point to the base directory, not the theme directory, i.e. `basePath=/home/erolland/Desktop/fibeamer` or `basePath=.` should both work.

**Comment by Cdk29** [comment]
Ahhh indeed, I was too focus on the theme.

It now works perfectly, thanks :) Now I have I nice template. I will mentioned the origin of the template on the credit dia during my presentations along side publications, thank you very much.

**Comment by Witiko** [comment]
No problem, I am glad that it works for you! Perhaps you will decide to publish your theme later on?

**Comment by Cdk29** [comment]
If one day I am happy of my color themes I will a pull request yes.
